[package]
name = "ruscv"
version = "0.0.1"
authors = [ "PG_MANA <pg_mana@taprix.org>" ]
description = "The bootloader for RISC-V written in Rust"
keywords = ["bootloader"]
categories = ["os", "operating-system"]
license = "Apache-2.0"
[lib]
crate-type = ["staticlib"]

